"""Constants for Qwen SSC Subgoal Decomposition."""
VALID_STATE_PREDICATES = {
    'CLOSED', 'OPEN', 'ON', 'OFF', 'PLUGGED_IN', 'PLUGGED_OUT',
    'SITTING', 'LYING', 'CLEAN', 'DIRTY',
    'ONTOP', 'INSIDE', 'BETWEEN', 'NEXT_TO', 'FACING',
    'HOLDS_RH', 'HOLDS_LH'
}
VALID_ACTION_PREDICATES = {
    'DRINK', 'EAT', 'CUT', 'TOUCH', 'LOOKAT', 'WATCH', 'READ', 'TYPE',
    'PUSH', 'PULL', 'MOVE', 'SQUEEZE', 'SLEEP', 'WAKEUP',
    'RINSE', 'SCRUB', 'WASH', 'GRAB', 'SWITCHOFF', 'SWITCHON',
    'OPEN', 'CLOSE', 'WALK', 'FIND', 'TURNTO', 'SIT', 'STANDUP',
    'LIE', 'PUTIN', 'PUTBACK', 'PLUGIN', 'PLUGOUT', 'POUR', 'DROP'
}
ALL_VALID_PREDICATES = VALID_STATE_PREDICATES | VALID_ACTION_PREDICATES
# SYS_PROMPT 由主脚本传入
